In [ ]:
BLOCK A = CREATION AND INSPECTION

In [1]:
#TASK 1
import numpy as np

# 1. Create a 1-D array of numbers 1 to 20
arr = np.arange(1, 21)

print("1-D Array:")
print(arr)

print("\n Shape:", arr.shape)
print("Dtype:", arr.dtype)
print("Size:", arr.size)
print("Mean:", arr.mean())


1-D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Shape: (20,)
Dtype: int64
Size: 20
Mean: 10.5


In [2]:
#TASK 2
identity_matrix = np.eye(5)

print("\n 5x5 Identity Matrix:")
print(identity_matrix)

print("\n Sum of identity matrix:", identity_matrix.sum())



5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Sum of identity matrix: 5.0


In [3]:
#TASK 3
matrix = np.zeros((3, 4))

# Turn the middle columns into 1s
matrix[:, 1:3] = 1

print("\n 3x4 Matrix with middle columns as 1s:")
print(matrix)


3x4 Matrix with middle columns as 1s:
[[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]]


In [4]:
#TASK 4
points = np.linspace(0, 2 * np.pi, 9)
sine_values = np.sin(points)

print("\n Points from 0 to 2π:")
print(points)

print("\n Sine values:")
print(sine_values)



Points from 0 to 2π:
[0.         0.78539816 1.57079633 2.35619449 3.14159265 3.92699082
 4.71238898 5.49778714 6.28318531]

Sine values:
[ 0.00000000e+00  7.07106781e-01  1.00000000e+00  7.07106781e-01
  1.22464680e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
 -2.44929360e-16]


In [5]:
#TASK 5
np.random.seed(42)

random_matrix = np.random.randint(0, 100, (4, 4))

print("\n 4x4 Random Integer Matrix:")
print(random_matrix)

print("\n Shape:", random_matrix.shape)
print("Minimum value:", random_matrix.min())
print("Maximum value:", random_matrix.max())
print("Mean:", random_matrix.mean())


4x4 Random Integer Matrix:
[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]

Shape: (4, 4)
Minimum value: 2
Maximum value: 99
Mean: 56.75


In [ ]:
BLOCK B = INDEXING AND SLICING

In [6]:
#TASK 1
a = np.arange(20)

print("Array:", a)

# First 5 items
print("First 5 items:", a[:5])

# Last 3 items
print("Last 3 items:", a[-3:])

# Items at even positions
print("Items at even positions:", a[::2])

# Reversed array
print("Reversed array:", a[::-1])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
First 5 items: [0 1 2 3 4]
Last 3 items: [17 18 19]
Items at even positions: [ 0  2  4  6  8 10 12 14 16 18]
Reversed array: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [7]:
#TASK 2
matrix = np.random.randint(1, 100, (5, 5))

print("\n5x5 Matrix:\n", matrix)

# First row
print("First row:", matrix[0])

# Last column
print("Last column:", matrix[:, -1])

# Centre 3x3 sub-matrix
print("Centre 3x3 sub-matrix:\n", matrix[1:4, 1:4])

# Main diagonal
print("Main diagonal:", np.diag(matrix))


5x5 Matrix:
 [[ 2 88 30 38  2]
 [64 60 21 33 76]
 [58 22 89 49 91]
 [59 42 92 60 80]
 [15 62 62 47 62]]
First row: [ 2 88 30 38  2]
Last column: [ 2 76 91 80 62]
Centre 3x3 sub-matrix:
 [[60 21 33]
 [22 89 49]
 [42 92 60]]
Main diagonal: [ 2 60 89 60 62]


In [8]:
#TASK 3
m = np.random.randint(1, 100, (4, 4))

print("\n Original 4x4 Matrix:\n", m)

m[m > 50] = -1

print("Modified Matrix:\n", m)



Original 4x4 Matrix:
 [[51 55 64  3]
 [51  7 21 73]
 [39 18  4 89]
 [60 14  9 90]]
Modified Matrix:
 [[-1 -1 -1  3]
 [-1  7 21 -1]
 [39 18  4 -1]
 [-1 14  9 -1]]


In [9]:
#TASK 4
a = np.arange(100)

result = a[(a % 3 == 0) & (a % 5 == 0)]

print("\n Numbers divisible by both 3 and 5:")
print(result)


Numbers divisible by both 3 and 5:
[ 0 15 30 45 60 75 90]


In [10]:
#TASK 5
scores = np.array([25, 78, 40, 33, 90, 55, 12])

result = np.where(scores < 40, "fail", "pass")

print("\n Scores:", scores)
print("Result:", result)


Scores: [25 78 40 33 90 55 12]
Result: ['fail' 'pass' 'pass' 'fail' 'pass' 'pass' 'fail']


In [ ]:
BLOCK C = BROADCASTING

In [11]:
#TASK 1
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

arr = np.array([100, 200, 300])

result = matrix + arr

print("Original Matrix:\n", matrix)
print("\n 1-D Array:", arr)
print("\n After Adding to Every Row:\n", result)

Original Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

1-D Array: [100 200 300]

After Adding to Every Row:
 [[101 202 303]
 [104 205 306]
 [107 208 309]
 [110 211 312]]


In [12]:
#TASK 2
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

column_vector = np.array([[10],
                          [20],
                          [30],
                          [40]])

result = matrix + column_vector

print("\n Original Matrix:\n", matrix)
print("\n Column Vector:\n", column_vector)
print("\n After Adding to Every Column:\n", result)


Original Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Column Vector:
 [[10]
 [20]
 [30]
 [40]]

After Adding to Every Column:
 [[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]]


In [13]:
#TASK 3
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

outer_product = a[:, np.newaxis] * b

print("\n Array a:", a)
print("Array b:", b)

print("\n Outer Product:\n", outer_product)



Array a: [1 2 3]
Array b: [4 5 6]

Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [14]:
#TASK 4
matrix = np.random.randint(1, 100, (5, 4))

print("\nOriginal Matrix:\n", matrix)

# Mean of each column
mean = matrix.mean(axis=0)

# Standard deviation of each column
std = matrix.std(axis=0)

# Standardisation
standardised = (matrix - mean) / std

print("\n Column Means:", mean)
print("Column Std Dev:", std)

print("\n Standardised Matrix:\n", standardised)


Original Matrix:
 [[53  2 84 92]
 [60 71 44  8]
 [47 35 78 81]
 [36 50  4  2]
 [ 6 54  4 54]]

Column Means: [40.4 42.4 42.8 47.4]
Column Std Dev: [18.91665932 23.22584767 34.49289782 36.81086796]

Standardised Matrix:
 [[ 0.66607955 -1.73944136  1.19444879  1.21159871]
 [ 1.03612375  1.2313867   0.03478977 -1.07033608]
 [ 0.34889881 -0.31861055  1.02049994  0.91277391]
 [-0.23259921  0.32722164 -1.12486925 -1.23333142]
 [-1.81850291  0.49944356 -1.12486925  0.17929488]]


In [ ]:
BLOCK D = MATH OPERATION

In [15]:
#TASK 1
values = np.linspace(0, 2 * np.pi, 10)

print("Values:\n", values)

print("\n Sin values:\n", np.sin(values))
print("\n Cos values:\n", np.cos(values))
print("\n Tan values:\n", np.tan(values))


Values:
 [0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]

Sin values:
 [ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]

Cos values:
 [ 1.          0.76604444  0.17364818 -0.5        -0.93969262 -0.93969262
 -0.5         0.17364818  0.76604444  1.        ]

Tan values:
 [ 0.00000000e+00  8.39099631e-01  5.67128182e+00 -1.73205081e+00
 -3.63970234e-01  3.63970234e-01  1.73205081e+00 -5.67128182e+00
 -8.39099631e-01 -2.44929360e-16]


In [16]:
#TASK 2
x = np.arange(1, 13).reshape(3, 4)

print("\n Matrix x:\n", x)

max_position = np.unravel_index(x.argmax(), x.shape)

print("\n Position of maximum value (row, col):", max_position)


 Matrix x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Position of maximum value (row, col): (np.int64(2), np.int64(3))


In [17]:
#TASK 3
a = np.array([5, 10, 15, 20, 25])

mean = a.mean()
std = a.std()

standardised = (a - mean) / std

print("\n Original Array:", a)
print("Mean:", mean)
print("Std Dev:", std)

print("\n Standardised Array:", standardised)

# Verify mean and std
print("\n Mean after standardisation:", standardised.mean())
print("Std after standardisation:", standardised.std())


 Original Array: [ 5 10 15 20 25]
Mean: 15.0
Std Dev: 7.0710678118654755

 Standardised Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

 Mean after standardisation: 0.0
Std after standardisation: 0.9999999999999999


In [18]:
#TASK 4
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

dot_product = np.dot(a, b)

print("\n Array a:", a)
print("Array b:", b)

print("\n Dot Product:", dot_product)

# Matrix product
m1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

m2 = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

matrix_product = np.matmul(m1, m2)

print("\n Matrix 1:\n", m1)
print("\n Matrix 2:\n", m2)

print("\n Matrix Product:\n", matrix_product)


 Array a: [1 2 3 4 5]
Array b: [ 6  7  8  9 10]

 Dot Product: 130

 Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

 Matrix Product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [19]:
#TASK 5
a = np.array([-10, -3, 0, 4, 7, 12, 100])

clipped = np.clip(a, 0, 10)

print("\n Original Array:", a)
print("Clipped Array:", clipped)


 Original Array: [-10  -3   0   4   7  12 100]
Clipped Array: [ 0  0  0  4  7 10 10]


In [ ]:
BLOCK E = RESHAPING AND COMBINING

In [21]:
#TASK 1
import numpy as np

a = np.arange(24)

print("Original Array:\n", a)

# Reshape into (2, 12)
print("\n Shape (2, 12):")
print(a.reshape(2, 12))

# Reshape into (3, 8)
print("\n Shape (3, 8):")
print(a.reshape(3, 8))

# Reshape into (4, 6)
print("\n Shape (4, 6):")
print(a.reshape(4, 6))

# Reshape into (2, 3, 4)
print("\n Shape (2, 3, 4):")
print(a.reshape(2, 3, 4))

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

 Shape (2, 12):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

 Shape (3, 8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

 Shape (4, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

 Shape (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [22]:
#TASK 2
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Stack as rows
row_stack = np.vstack((a, b))

# Stack as columns
column_stack = np.column_stack((a, b))

print("\n Array a:", a)
print("Array b:", b)

print("\n 2-row Matrix:\n", row_stack)

print("\n 2-column Matrix:\n", column_stack)


 Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]

 2-row Matrix:
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]

 2-column Matrix:
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]


In [23]:
#TASK 3
arr = np.arange(20)

print("\n Original Array:\n", arr)

# Split into 4 equal parts
parts = np.split(arr, 4)

print("\n Split Parts:")
for i, part in enumerate(parts):
    print(f"Part {i+1}:", part)

# Concatenate first and third parts
combined = np.concatenate((parts[0], parts[2]))

print("\n Concatenated First and Third Parts:")
print(combined)


 Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 Split Parts:
Part 1: [0 1 2 3 4]
Part 2: [5 6 7 8 9]
Part 3: [10 11 12 13 14]
Part 4: [15 16 17 18 19]

 Concatenated First and Third Parts:
[ 0  1  2  3  4 10 11 12 13 14]


In [ ]:
BLOCK F = MINI PROJECT